jobs:
    build-and-test:
        docker:
            - image: cimg/node:16.10
        steps:
            - checkout
            - node/install-packages:
                  pkg-manager: pnpm
            - run:
                  name: Run tests
                  command: pnpm test
